import fs from 'fs';

const out = 'houdini-snowflake.js';

const properties = fs.readFileSync('properties.js');

const worklet = fs.readFileSync('worklet.js');

const template = `/* 
 * This file is autogenerated.
 * ${out} 
 * https://github.com/zhenyanghua/houdini/tree/master/snowflake
 */
 
${properties}
(() => { const worklet = \`
${worklet}\`;

const workletBlob = URL.createObjectURL(new Blob([worklet], { type: 'application/javascript' }));

window.CSS.paintWorklet.addModule(workletBlob);
})();
`;

fs.writeFileSync(out, template);

